import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './providers' // Import AuthProvider

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Manual Next App', // Or your preferred title
  description: 'Generated by manual setup', // Or your preferred description
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider> {/* Wrap children with AuthProvider */}
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
